### ISSUE TITLE
Release built binary file

### ISSUE THREAD

**Issue by Hayao0819** [xiaomi-sm6375-devs/android_device_xiaomi_veux#1]
Thank you for making device tree for Veux.

I want to use it , however, I do not have time to build it myself.

Could you release built recovery image file?

**Comment by kleidione** [comment]
You can use the one from lineage during installation it will be replaced by the one from Pixel

**Comment by kleidione** [comment]
The tree creator is Ramii ahmed I just keep a fork

**Comment by Ramisky** [comment]
It's released, you could check my telegram group t.me/ramiskychat, I push release links there
