### ISSUE TITLE
Add simple build instructions to README

### ISSUE THREAD

**Issue by denysonique** [xiaomi-sm6375-devs/android_device_xiaomi_veux#2]
I would like to start testing out Lineage OS on veux however I do not know where to find or how to create a local manifest for `repo`.

Simple steps how to build for veux would be very helpful.

**Comment by ghost** [comment]
That's not a thing you usally add to a `README.md` of a device tree, you usally get those `repo` commands from the manifest of the ROM.

**Comment by denysonique** [comment]
In this case having this question answered here as an issue comment would be very helpful, alternatively a wiki page could be created for that. I really would like to help with testing Lineage OS on Veux.

**Comment by Ramisky** [comment]
> In this case having this question answered here as an issue comment would be very helpful, alternatively a wiki page could be created for that. I really would like to help with testing Lineage OS on Veux.

You could use this as reference https://wiki.lineageos.org/devices/apollon/build some logic needed (not much tho) to get it working, enjoy ;)
